version: '3.8'

services:
  cats-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/zeiterfassung.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/entries"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s